### ISSUE TITLE
I get an error...

### ISSUE THREAD

**Issue by doriansgithub** [sbooth/SFBCrashReporter#6]
ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a

**Comment by sbooth** [comment]
That's not much to go on. Without more information it's difficult to even hazard a guess about the cause.

**Comment by doriansgithub** [comment]
I just ran it and that's what I get. When I open the project, it loads as a framework, but in the folder, I don't see a framework, so I can't load it as a framework on my project. This is the same on both on the crashreporter and the popups.

**Comment by doriansgithub** [comment]
I also have a question on the sfbaudioengine, is it possible to use the metadata classes without using the sfbplayer? I want my project to be able to read 128, 256, & 512 DSDs, which sfbplayer can't, but the metadata of sfb is very very good. Thanks, Dorian
